### ISSUE TITLE
Parse dataset configurations and write loading code for NSD-Synthetic

### ISSUE THREAD

**Issue by reesekneeland** [MedARC-AI/MindEye_Imagery#7]
All of the files and documentation I have available for NSD-Synthetic are in the Datasets folder on google drive. This is not data that I have explored before, and it does not have code to streamline the loading process for it. We need someone to go through the documentation and experiment with loading associated betas and stimuli from the included files. This would be a great item for someone with limited or no GPU compute to work on while we continue alleviating those blockers.

**Comment by mihirneal** [comment]
lemme get on this

**Comment by reesekneeland** [comment]
This has been finished as of last commit, see the dataset_preparation branch and the new data loading methods in utils file of main branch.
